---
title: "3 - Désaisonnalisation sans correction des jours ouvrables"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = FALSE, warning = FALSE,
                      message = FALSE)
library(knitr)
```

> L'objectif de ce TP est d'apprendre à faire une désaisonnalisation sans correction des jours ouvrables (CJO).

# Réaliser une désaisonnalisation automatique sans correction des effets de calendrier

-   Créer un nouveau workspace.

-   Sauvegarder le workspace.

-   Importer les séries (si nécessaire).

-   Créer un nouveau multi-document : `Statistical methods > Seasonal Adjustment > Multi Processing > New`.

-   Renommer le "SAProcessing-1" ("X13-RSA1" par exemple) en faisant un clic droit sur son nom sous l'onglet `Workspace > multi-documents` puis `Rename...`

-   Réaliser une désaisonnalisation automatique de ces séries en choisissant la spécification pré-définie `X13 > RSA3`.


# Analyser des paramètres automatiques choisis par JDemetra+

Pour chaque série :

## Schéma de décomposition

-   Dans la fenêtre `Main results` :

    -   Quel est le schéma de décomposition choisi par JDemetra+ ? Est-ce que vous êtes d'accord ?

## Outliers

-   Dans la fenêtre `Main results` :

    -   Combien d'*outliers* ont été détectés par JDemetra+ ?

        -   Y en a-t-il trop ?

-   Dans la fenêtre `Pre-processing` :

    -   Quels sont les différents types d'outliers détéctés par JDemetra+ ?

-   Retourner dans la fenêtre `Main results` :

    -   Aller dans `Main results > Charts` :

        -   Regarder les différents graphiques : pouvez-vous repérer, sur la série brute, les points atypiques détéctés dans le modèle ?

## S-I Ratio

-   Aller dans la fenêtre `Main results > S-I ratio`.

-   Pouvez-vous repérer le schéma de décomposition ?

-   Quel est l'objectif de ce graphique ?

-   Les coefficients saisonniers sont-ils stables ?

# Analyse de la qualité de la désaisonnalisation

Pour chaque série, parcourir les diagnostics disponibles dans `Main results` :

-   Quelle est la qualité de la phase de pré-ajustement ? (`Regarima residuals` et `outliers`)

-   Quelle est la qualité de la décomposition (X11) ? (`M-Statistics`)

-   La série CVS présente-t-elle des effets saisonniers résiduels ?

-   La série CVS présente-t-elle des effets « jours ouvrables » résiduels ?
