---
title: "7 - Étude de cas"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = FALSE, warning = FALSE,
                      message = FALSE)
library(knitr)
library(RJDemetra)
options(enable_print_style = FALSE)
dir = "."
if (!file.exists("Etude_de_cas.xml")) {
# 	dir <- tempdir()
# download.file("https://aqlt.github.io/formation.2025.cvs/data/Etude_de_cas.zip",
#               file.path(dir, "Etude_de_cas.zip"))
# unzip(file.path(dir, "Etude_de_cas.zip"),
#       exdir = dir)
}
```

> L'objectif de ce TP est de faire une étude de cas spécifique pour voir des problèmes possibles et une proposition de solution.

Disclaimer : il peut exister plusieurs solutions, celles données dans ce TP ne sont que des propositions qui peuvent être discuté.

Pour télécharger le workspace, cliquer [ici](/data/Etude_de_cas.zip) et dézipper le fichier.
Les données utilisées sont des indices de production industrielle (IPI) ou des indices de chiffres d'affaires (ICA)

<!-- ```{r} -->
<!-- #| eval: false -->
<!-- dir <- tempdir() -->
<!-- download.file("https://aqlt.github.io/formation.2023.cvsdata/Etude_de_cas.zip", -->
<!--               file.path(dir, "Etude_de_cas.zip")) -->
<!-- unzip(file.path(dir, "Etude_de_cas.zip"), -->
<!--       exdir = dir) -->
<!-- u_def_var <- c("diagnostics.td-sa-last", "diagnostics.td-i-last", -->
<!--                "diagnostics.fcast-insample-mean", "diagnostics.fcast-outsample-mean", -->
<!--                "diagnostics.fcast-outsample-variance") -->
<!-- jws <- load_workspace(file.path(dir, "Etude_de_cas.xml")) -->
<!-- compute(jws) -->
<!-- all_models <- get_model(jws, -->
<!--             userdefined = u_def_var)[[1]] -->
<!-- all_models$RF2932 -->
<!-- ``` -->

# Pré-ajustement

## Série RF2932 (IPI, Fabrication d'autres équipements automobiles)

::: callout-note
## Exercice
Il y a un problème d'hétéroscédasticité (au seuil de 1 %) et un léger problème de non-normalité (au seuil de 1 %).
:::

::: {.callout-caution collapse="true"}
## Indice
Que pensez-vous du schéma de décomposition ?
:::

::: {.callout-tip collapse="true"}
## Solution
Décision : forcer le schéma en multiplicatif.
:::

<!-- ::: {.callout-tip collapse="true"} -->
<!-- ## Solution avec `RJDemetra` -->
<!-- ```{r} -->
<!-- RF2932_init <- x13(get_ts(all_models$RF2932), -->
<!--                    x13_spec(all_models$RF2932), -->
<!--                    userdefined = c("diagnostics.levelstat", -->
<!--                                    "diagnostics.logstat")) -->
<!-- # avec modèle airline, le modèle additif est meilleur en terme d'aicc -->
<!-- c(RF2932_init$user_defined)  -->
<!-- RF2932_init$regarima$residuals.stat -->
<!-- summary(RF2932_init$regarima) -->
<!-- plot(get_ts(RF2932_init)) # schéma parait plutôt multiplicatif -->
<!-- RF2932 <- x13(get_ts(RF2932_init), -->
<!--               x13_spec(RF2932_init, -->
<!--                        transform.function = "Log")) -->
<!-- # critères d'information plus petits avec le modèle ARIMA final -->
<!-- summary(RF2932$regarima)  -->
<!-- RF2932$regarima$residuals.stat -->
<!-- ``` -->
<!-- ::: -->

## Série RF2813 (IPI, Fabrication d'autres pompes et compresseurs)

L'analyse de cette série nécessite d'avoir vu les statistiques M qui jugent la qualité de la décomposition.

::: callout-note 
## Exercice
Il y a un problème d'autocorrélation des résidus (au seuil de 1 %) et une mauvaise décomposition (Q-M2). 
::: 

::: {.callout-caution collapse="true"}
## Indice
Que pensez-vous du schéma de décomposition ?
:::

::: {.callout-tip collapse="true"}
## Solution
Le problème d'autocorrélation peut être atténué en forçant le schéma additif (p-valeur du test est alors égale à 0,04). 

La mauvaise décomposition vient du fait que la tendance est plate et donc que la composante irrégulière est plus variable que la composante tendance-cycle.

Décision : forcer le schéma en additif.
:::

## Série RF2223 (IPI, Fabrication d'éléments en matières plastiques pour la construction)

::: callout-note 
## Exercice
Il y a un effet JO résiduel (au seuil de 5 % mais pas 1 %) et un problème d'hétéroscédasticité (au seuil de 5 % mais pas 1 %).
::: 

::: {.callout-caution collapse="true"}
## Indice
Réduire le seuil de détection des outliers pour voir ce qu'il se passe.
:::

::: {.callout-tip collapse="true"}
## Solution
Décision : Ajouter deux AO en 8-2007 et 7-2009.

Il est préférable de rajouter les outliers à la main plutôt que de modifier de manière permanente le seuil de détection des outliers : cela évitera, pour les futures révisions du modèle,de détecter trop d'outliers.
:::

<!-- ::: {.callout-tip collapse="true"} -->
<!-- ## Solution avec `RJDemetra` -->
<!-- ```{r} -->
<!-- RF2223_init <- all_models$RF2223 -->
<!-- RF2223_init$regarima$residuals.stat -->
<!-- summary(RF2223_init$regarima) -->
<!-- # Pas d'effet JO résiduel sur l'ensemble de la série -->
<!-- RF2223_init$diagnostics -->
<!-- # Mais effet JO résiduel si test sur 8 dernières années -->
<!-- c(RF2223_init$user_defined) -->
<!-- RF2223 <- x13(get_ts(RF2223_init), -->
<!--               x13_spec(RF2223_init, -->
<!--                        outlier.usedefcv = FALSE, -->
<!--                        outlier.cv = 2.8), -->
<!--               userdefined = u_def_var) -->
<!-- summary(RF2223$regarima) -->
<!-- # Plus d'effet résiduel -->
<!-- c(RF2223$user_defined) -->

<!-- # Pour rajouter les outliers à la main -->
<!-- RF2223 <- x13(get_ts(RF2223_init), -->
<!--               x13_spec(RF2223_init, -->
<!--                        usrdef.outliersEnabled = TRUE, -->
<!--                        usrdef.outliersType = c("AO", "AO"), -->
<!--                        usrdef.outliersDate = c("2008-04-01", "2009-07-01")), -->
<!--               userdefined = u_def_var) -->
<!-- summary(RF2223$regarima) -->
<!-- ``` -->
<!-- ::: -->

## Série RF2453 (IPI, Fonderie de métaux légers) : TC or not TC

::: callout-note 
## Exercice
Il y a un effet JO résiduel (au seuil de 1 %).
::: 

::: {.callout-caution collapse="true"}
## Indice
Que pensez-vous des outliers détectés ?
:::

::: {.callout-tip collapse="true"}
## Solution
Supprimer la détection des TC permet de corriger le problème sur l'irrégulier mais pas sur la série désaisonnalisée.

Décision : désactiver la détection automatique de TC.
:::

<!-- ::: {.callout-tip collapse="true"} -->
<!-- ## Solution avec `RJDemetra` -->
<!-- ```{r} -->
<!-- RF2453_init <- all_models$RF2453 -->
<!-- RF2453_init$regarima$residuals.stat -->
<!-- # Pas d'effet JO résiduel sur l'ensemble de la série -->
<!-- RF2453_init$diagnostics -->
<!-- # Mais effet JO résiduel si test sur 8 dernières années -->
<!-- c(RF2453_init$user_defined) -->
<!-- # Beaucoup de TC qui se suivent -->
<!-- summary(RF2453_init$regarima) -->

<!-- # Pour rajouter les outliers à la main -->
<!-- RF2453 <- x13(get_ts(RF2453_init), -->
<!--               x13_spec(RF2453_init, -->
<!--                        outlier.tc = FALSE), -->
<!--               userdefined = u_def_var) -->
<!-- summary(RF2453$regarima) -->
<!-- c(RF2453$user_defined) -->
<!-- ``` -->
<!-- ::: -->

# S-I Ratio

## Série RF1101 (IPI, Production de boissons alcooliques distillées)

::: callout-note
## Exercice
Analyser les S-I ratios et le graphique *yearly components* de la série brute : que remarquez vous ?
:::

::: {.callout-tip collapse="true"}
## Solution
Pour cette série, le modèle est estimé depuis 2004 mais les CVS-CJO ne sont mises à jour qu'à partir de 2012.

Il y a une nette rupture de saisonnalité en 2008 qui n'affecte pas la période après 2012 (filtre M3X5 utilisé, soit pour l'estimation des coefficients saisonniers de l'année A utilise les moyennes de l'année A-3 à A+3). 
Ainsi, commencer l'estimation du modèle à partir de 2008 permet d'avoir un modèle de pré-ajustement mieux estimé sur le présent et la rupture de saisonnalité n'affectera pas les coefficients publiés. 

Une autre solution est de rajouter un seasonal outlier en août 2008.
:::

# Saisonnalité résiduelle

## Série RF2561 (IPI, Traitement et revêtement des métaux)

::: callout-note 
## Exercice
Il y a de la saisonnalité résiduelle et une mauvaise qualité des résidus du modèle RegARIMA.
::: 

::: {.callout-caution collapse="true"}
## Indice
Analyser la série sur la fin de la période pour voir d'où vient la saisonnalité résiduelle. Comment pourrait-on la corriger ? Est-ce qu'il s'agit d'une rupture brute ou progressive ?
:::

::: {.callout-tip collapse="true"}
## Solution
Une rupture de saisonnalité s'observe en juin 2011 : avant cette date juin était un point haut alors qu'à partir de 2011 il est au même niveau que les mois de mai et juillet. 
Ajout un SO à cette date corrige la rupture mais laisse une saisonnalité résiduelle qui vient du mois de décembre : on observe sur la série désaisonnalisée des pics systématiques en décembre sur les dernières années.
Cette fois-ci ce n'est pas une rupture brute de la saisonnalité : le point de décembre qui était également un point haut avant 2011 devient progressivement de plus en plus bas. 
Le MSR de décembre (à 0,77) est d'ailleurs bien plus bas que celui des autres mois (qui sont autour de 2) ce qui suggère de prendre un filtre saisonnier plus court en décembre (le filtre actuellement choisi est M3X3). 
La mauvaise qualité des résidus est difficilement corrigeable, il faudrait prendre une période d'estimation beaucoup plus courtes qui ajouterait donc une instabilité des estimations.

Décision : rajouter un SO en juin 2011 et utiliser le filtre M3X1 pour le mois de décembre. 
Pas d'intervention pour corriger la qualité des résidus.
:::


## Série RF3299 (IPI, Autres activités manufacturières n.c.a.)

::: callout-note 
## Exercice
Il y a de la saisonnalité résiduelle.
::: 

::: {.callout-caution collapse="true"}
## Indice
Analyser correctement le problème de saisonnalité résiduelle.
:::

::: {.callout-tip collapse="true"}
## Solution
Ajouter des SO en 10-2012 et 12-2015.
:::

## Séries C4672 (ICA, Commerce de gros de minerais et métaux)

::: callout-note
## Exercice
Dans cet exercice il y a deux séries à étudier : la série C4672 depuis 1999 et la même série mais estimée à partir de 2005.

- Commencez par la série qui commence en 1999. 
Comment vous parait le modèle ?

- Analyser le modèle de la série qui commence en 2005 et comparer les résultats.
:::

::: callout-note 
## Exercice
Saisonnalité résiduelle non détectée pour modèle ensemble mais détectée si modèle coupé à partir de 2005.
::: 

::: {.callout-tip collapse="true"}
## Solution
Ajouter un SO 11-2008.
:::

## Série C4773 (ICA, Commerce de détail de produits pharmaceutiques en magasin spécialisé)

::: callout-note 
## Exercice
Saisonnalité résiduelle détectée.
::: 

::: {.callout-caution collapse="true"}
## Indice
Étudier les S-I ratio : la saisonnalité est-elle stable ?
:::

::: {.callout-tip collapse="true"}
## Solution
On observe une saisonnalité plutôt stable sauf en juillet et août (étude des S-I ratio). 
Les S-I ratio montrent aussi en juillet et août un comportement « atypique » de l'irrégulier en début de période. 
On n'observe pas de changement brusque de saisonnalité.
L'étude des MSR par mois suggère de prendre un filtre plus court en juillet et en août : cela permet de corriger la saisonnalité résiduelle.
:::